In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):  #inheirate from nn.Module
    def __init__(self,num_features):

      super().__init__() # initilize the nn.Module from thi class
      self.linear = nn.Linear(num_features, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      out = self.linear(features) # z = w*x + b
      out = self.sigmoid(out) #sigmoid on z

      return out


In [4]:
#create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass
model(features)       # no model.forward(features) because nn.Module have overwrite the magic method

tensor([[0.3016],
        [0.2708],
        [0.4073],
        [0.3718],
        [0.2916],
        [0.3060],
        [0.3418],
        [0.3090],
        [0.3574],
        [0.2764]], grad_fn=<SigmoidBackward0>)

In [16]:
#magic method __call__
class MyClass:
    def __init__(self, value):
        self.value = value  # Store the initial value

    def add(self, x):
        self.value += x  # Add x to self.value
        return self.value

    def __call__(self, x):
        print(self.add(x))

# Create an instance
obj = MyClass(5)
obj(2)

7


In [7]:
#show weights of parameters
model.linear.weight

Parameter containing:
tensor([[-0.1177, -0.3179, -0.2706, -0.3993,  0.2984]], requires_grad=True)

In [8]:
#show bias
model.linear.bias

Parameter containing:
tensor([-0.2579], requires_grad=True)

In [17]:
!pip install torchinfo

In [19]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

##Level up / A bit complex network

In [32]:
class Model1(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.l1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.l2 = nn.Linear(3 , 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.l1(features)
    out = self.relu(out)
    out = self.l2(out)
    out = self.sigmoid(out)
    return out

In [33]:
features1 = torch.rand(20,5)

In [34]:
model1 = Model1(features1.shape[1])

In [37]:
model1(features1)

tensor([[0.6285],
        [0.6285],
        [0.6283],
        [0.6318],
        [0.6285],
        [0.6285],
        [0.6306],
        [0.6285],
        [0.6284],
        [0.6283],
        [0.6293],
        [0.6284],
        [0.6284],
        [0.6285],
        [0.6285],
        [0.6284],
        [0.6285],
        [0.6285],
        [0.6285],
        [0.6284]], grad_fn=<SigmoidBackward0>)

In [38]:
model1.l1.weight

Parameter containing:
tensor([[-0.2568,  0.0457,  0.2148, -0.3380, -0.2543],
        [-0.2363, -0.4354,  0.0400, -0.2265, -0.0235],
        [ 0.2452,  0.3620, -0.4448, -0.3277,  0.2637]], requires_grad=True)

In [39]:
summary(model1, input_size=(20,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [20, 1]                   --
├─Linear: 1-1                            [20, 3]                   18
├─ReLU: 1-2                              [20, 3]                   --
├─Linear: 1-3                            [20, 1]                   4
├─Sigmoid: 1-4                           [20, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## use of container

In [41]:
class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self, features):
    out = self.network(features)
    return out

In [42]:
model2 = Model2(features1.shape[1])

In [44]:
model2(features1)

tensor([[0.4863],
        [0.4920],
        [0.4788],
        [0.4829],
        [0.4847],
        [0.4698],
        [0.4895],
        [0.5043],
        [0.4957],
        [0.4998],
        [0.5081],
        [0.4735],
        [0.5074],
        [0.4665],
        [0.4858],
        [0.4774],
        [0.4590],
        [0.4755],
        [0.4951],
        [0.4818]], grad_fn=<SigmoidBackward0>)