In [66]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [67]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [68]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [69]:
df.shape

(569, 33)

In [70]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace=True)

In [71]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [72]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [73]:
pd.unique(y_train)

array(['B', 'M'], dtype=object)

In [74]:
#scalling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) # use transform not fit_transform as
#we use the same scaler We should use the same scaling parameters (mean & standard deviation) from the training data.

In [75]:
X_train[0]

array([-0.51241301, -0.27105112, -0.54275797, -0.54070625, -0.69531409,
       -0.68798283, -0.60331006, -0.63536701,  0.60300126, -0.06595145,
       -0.6652699 , -0.42079026, -0.68125494, -0.54321152, -0.50284031,
       -0.53457   , -0.39286664, -0.59556041, -0.32654551, -0.47893379,
       -0.53878532, -0.03314863, -0.60073501, -0.55507555, -0.45808289,
       -0.45955872, -0.35363477, -0.46416651,  0.3513935 , -0.11641707])

In [76]:
y_train

155    B
325    B
312    B
24     M
151    B
      ..
287    B
190    M
115    B
273    B
111    B
Name: diagnosis, Length: 455, dtype: object

In [77]:
#label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [78]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,

In [79]:
#Numpy arrays to PyTorch tensors
# X_train = torch.from_numpy(X_train)
# X_test = torch.from_numpy(X_test)
# y_train = torch.from_numpy(y_test)
# y_test = torch.from_numpy(y_test)

In [80]:
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train= torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [81]:
X_train

tensor([[-0.5124, -0.2711, -0.5428,  ..., -0.4642,  0.3514, -0.1164],
        [-0.3914, -0.4255, -0.4181,  ..., -0.8603, -0.3463, -0.8249],
        [-0.3654, -1.3740, -0.3746,  ..., -0.4338, -0.5499, -0.0475],
        ...,
        [-0.6046,  0.5954, -0.6155,  ..., -0.6105, -0.7568,  0.1165],
        [-1.2352, -0.8189, -1.2442,  ..., -0.9276, -0.0952, -0.0919],
        [-0.4029,  0.4095, -0.3805,  ..., -0.0331, -1.1048,  0.0852]])

In [82]:
# X_train = X_train.to(torch.float32)
# X_test = X_test.to(torch.float32)
# y_train = y_train.to(torch.float32)
# y_test = y_test.to(torch.float32)

In [83]:
X_train[0]

tensor([-0.5124, -0.2711, -0.5428, -0.5407, -0.6953, -0.6880, -0.6033, -0.6354,
         0.6030, -0.0660, -0.6653, -0.4208, -0.6813, -0.5432, -0.5028, -0.5346,
        -0.3929, -0.5956, -0.3265, -0.4789, -0.5388, -0.0331, -0.6007, -0.5551,
        -0.4581, -0.4596, -0.3536, -0.4642,  0.3514, -0.1164])

In [108]:
#defining the model
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features , 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self , x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x

In [109]:
#loss function
loss_function = nn.BCELoss()

In [110]:
learning_rate = 0.1
epochs = 50

In [111]:
#training pipeline
#create model
model = MySimpleNN(X_train.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

#define loop for epochs
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train)

  #loss calculate
  loss = loss_function(y_pred , y_train.view(-1,1))  #.view(-1,1)  shape will be (row_of_y_train , 1) in this case (455,1)

  #clear grad
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1} Loss: {loss.item()}')

Epoch: 1 Loss: 0.5356966853141785
Epoch: 2 Loss: 0.45386916399002075
Epoch: 3 Loss: 0.4013867676258087
Epoch: 4 Loss: 0.3641403317451477
Epoch: 5 Loss: 0.33598268032073975
Epoch: 6 Loss: 0.31375664472579956
Epoch: 7 Loss: 0.29565152525901794
Epoch: 8 Loss: 0.280544638633728
Epoch: 9 Loss: 0.2676984965801239
Epoch: 10 Loss: 0.25660622119903564
Epoch: 11 Loss: 0.2469065636396408
Epoch: 12 Loss: 0.23833417892456055
Epoch: 13 Loss: 0.2306893914937973
Epoch: 14 Loss: 0.22381854057312012
Epoch: 15 Loss: 0.21760131418704987
Epoch: 16 Loss: 0.21194200217723846
Epoch: 17 Loss: 0.20676328241825104
Epoch: 18 Loss: 0.20200200378894806
Epoch: 19 Loss: 0.19760605692863464
Epoch: 20 Loss: 0.19353190064430237
Epoch: 21 Loss: 0.18974290788173676
Epoch: 22 Loss: 0.18620796501636505
Epoch: 23 Loss: 0.182900533080101
Epoch: 24 Loss: 0.1797977089881897
Epoch: 25 Loss: 0.1768796741962433
Epoch: 26 Loss: 0.17412924766540527
Epoch: 27 Loss: 0.17153126001358032
Epoch: 28 Loss: 0.1690724641084671
Epoch: 29 Loss

In [112]:
#when model is initialized then model.parameters will register all the weights and bias in the form of interations like as below:
for i in model.parameters():
  print(i)

Parameter containing:
tensor([[ 0.3005,  0.2814,  0.4071,  0.1330,  0.2417,  0.2607,  0.0522,  0.1325,
          0.0471, -0.0667,  0.3600, -0.1503,  0.3777,  0.3194,  0.1137, -0.1247,
         -0.0967,  0.0329, -0.1512,  0.0360,  0.3642,  0.4164,  0.3466,  0.3443,
          0.0500,  0.1939,  0.3773,  0.3932,  0.2653, -0.0095]],
       requires_grad=True)
Parameter containing:
tensor([-0.1849], requires_grad=True)


In [113]:
#evaluation
with torch.no_grad():
  y_pred = model.forward(X_test)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.5124653577804565
