##Tensors in pytorch

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available !")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}" )
else:
  print("GPU not available, Using CPU")

GPU not available, Using CPU


##Creating a Tensor

In [ ]:
#using empty
torch.empty(2,3)

tensor([[1.3606e-31, 4.5493e-41, 1.3606e-31],
        [4.5493e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

In [ ]:
#using seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [ ]:
#using seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#some other methods

#arrange
print("using arrange ->",torch.arange(0,10))

#using linspace
print("using linspace ->", torch.linspace(0,10,10))

#using eye
print("using eye ->",torch.eye(5))

#using full
print("using full ->",torch.full((3,3),5))

using arrange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


##Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[           37854144,            39443520, 4614688418536882176],
        [4616690018251964416, 4617941017671237632, 4619192017627381760]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x) #see it later

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7689, 0.7215, 0.2644],
        [0.7745, 0.4324, 0.4453]])

##Data types in Tensor

In [ ]:
#find data type
x.dtype

torch.int64

In [ ]:
#assign the datatype
x = torch.tensor([1.0,2.0,3.0] , dtype=torch.int32)
x

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#using to() --> conversion of datatype
x.to(torch.float32)

tensor([1., 2., 3.])

##Mathematical operation

In [ ]:
#addition
x + 2

#substraction
x-2

#multiplication
x * 2

#division
x / 2

#int division
(x * 100) // 2

#mod
((x * 100 ) // 2 ) % 2

#power
(x ** 2)

tensor([[ 1,  4,  9],
        [16, 25, 36]])

##ELement wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8856, 0.2801, 0.0722],
        [0.1181, 0.0556, 0.8835]])
tensor([[0.0250, 0.2980, 0.7826],
        [0.9575, 0.2881, 0.9790]])


In [ ]:
#addition
a + b

#sub
a - b

#multiply
a * b

#division
a / b

#power
a ** b

#mod
a % b


tensor([[0.0092, 0.2801, 0.0722],
        [0.1181, 0.0556, 0.8835]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.0,2.3,4.7,4.4])

In [ ]:
#round
torch.round(d)

tensor([1., 2., 5., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([1., 3., 5., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 4., 4.])

In [ ]:
#clamp
torch.clamp(d,min=2,max=4)

tensor([2.0000, 2.3000, 4.0000, 4.0000])

##Reduction operation

In [ ]:
e = torch.randint(size=(2,3),low = 0 , high = 10)

In [ ]:
e

tensor([[9, 6, 1],
        [5, 3, 3]])

##Tensor operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
device

device(type='cuda')

In [ ]:
#creating new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3420, 0.5989, 0.6775],
        [0.2770, 0.2269, 0.1728]], device='cuda:0')

In [ ]:
#moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.7316, 0.2402, 0.4321],
        [0.7853, 0.9165, 0.1479]])

In [ ]:
b = a.to(device)

In [ ]:
b

tensor([[0.7316, 0.2402, 0.4321],
        [0.7853, 0.9165, 0.1479]], device='cuda:0')

In [ ]:
import time
size = 10000

a = torch.rand(size , size)
b = torch.rand(size , size)

#on cpu
start_time = time.time()
result_cpu = torch.matmul(a , b) #on cpu
end_time = time.time()
print(f"Time taken by CPU: {end_time - start_time}")


#on GPU
a = a.to(device)
b = b.to(device)
start_time = time.time()
result_gpu = torch.matmul(a , b) #on gpu
end_time = time.time()
print(f"Time taken by GPU: {end_time - start_time}")




Time taken by CPU: 25.82455015182495
Time taken by GPU: 0.025361061096191406


##Autograd
Autograd is a core component of pyTorch that provides automatic differentiation for tensor operations. It enables gradient computation, which is essential for trainig machine learning models using optimization algorithms like gradient descent

In [3]:
import torch

In [3]:
x = torch.tensor(3.0 , requires_grad = True)

In [4]:
x

tensor(3., requires_grad=True)

In [5]:
y = x ** 2

In [6]:
y

tensor(9., grad_fn=<PowBackward0>)

In [7]:
y.backward() #automatically calculate all the gradient

In [9]:
x.grad #to view the result

tensor(6.)

In [6]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [7]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [22]:
z = torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [23]:
z.backward()

In [24]:
x.grad

tensor(-5.4668)

In [12]:
#test
a = torch.tensor(2.0 , requires_grad=True)
a

tensor(2., requires_grad=True)

In [34]:
b = a ** 2
b

tensor(4., grad_fn=<PowBackward0>)

In [35]:
b.backward()

In [36]:
a.grad

tensor(4.)

In [37]:
a.grad.zero_()  #removes the gradient of the previously caluclated .

tensor(0.)