In [2]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

In [18]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [19]:
df.describe()

id  radius_mean  ...  fractal_dimension_worst  Unnamed: 32
count  5.690000e+02   569.000000  ...               569.000000          0.0
mean   3.037183e+07    14.127292  ...                 0.083946          NaN
std    1.250206e+08     3.524049  ...                 0.018061          NaN
min    8.670000e+03     6.981000  ...                 0.055040          NaN
25%    8.692180e+05    11.700000  ...                 0.071460          NaN
50%    9.060240e+05    13.370000  ...                 0.080040          NaN
75%    8.813129e+06    15.780000  ...                 0.092080          NaN
max    9.113205e+08    28.110000  ...                 0.207500          NaN

[8 rows x 32 columns]

In [20]:
df.shape

(569, 33)

In [21]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace=True)

In [22]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [27]:
pd.unique(y_train)

array(['B', 'M'], dtype=object)

In [28]:
#scalling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) # use transform not fit_transform as
#we use the same scaler We should use the same scaling parameters (mean & standard deviation) from the training data.

In [30]:
X_train[0]

array([ 2.95734584e-03,  2.93310301e-01, -2.72561063e-04, -1.20544917e-01,
       -5.05938063e-01,  9.60101634e-02, -4.89101517e-01, -4.86993924e-01,
       -1.11268818e+00, -3.97765808e-01, -2.18007490e-01, -3.43696927e-01,
       -7.68838208e-02, -2.11678819e-01, -9.41115562e-01,  3.89204482e-01,
       -1.17728392e-01,  2.91196647e-01, -5.36459572e-01, -4.38014039e-01,
        1.87735618e-02,  2.55960418e-01,  1.23161763e-01, -1.07515209e-01,
       -7.38557062e-01,  5.10377843e-01, -1.17019761e-01,  2.63212444e-01,
       -5.99083866e-01, -3.20070831e-01])

In [31]:
y_train

476    B
38     M
252    M
47     M
543    B
      ..
307    B
405    B
471    B
206    B
24     M
Name: diagnosis, Length: 455, dtype: object

In [32]:
#label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [33]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,

In [ ]:
#Numpy arrays to PyTorch tensors
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_test)
y_test = torch.from_numpy(y_test)

In [37]:
X_train

tensor([[ 2.9573e-03,  2.9331e-01, -2.7256e-04,  ...,  2.6321e-01,
         -5.9908e-01, -3.2007e-01],
        [ 2.2410e-01,  1.3810e+00,  1.2700e-01,  ..., -1.2924e+00,
         -2.1342e+00, -1.5610e+00],
        [ 1.5509e+00,  1.2794e-01,  1.5566e+00,  ...,  1.9952e+00,
         -2.5848e-01,  2.3748e+00],
        ...,
        [-6.0168e-01,  2.0658e+00, -6.3295e-01,  ..., -8.9977e-01,
         -8.0503e-01, -9.6269e-01],
        [-1.2074e+00, -4.6600e-01, -1.1994e+00,  ..., -8.9369e-01,
          1.2173e-01, -5.7206e-01],
        [ 6.8877e-01,  4.9129e-01,  7.1495e-01,  ...,  1.3842e+00,
          1.1103e+00,  5.7927e-01]], dtype=torch.float64)

In [68]:
#defining the model

class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64 , requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X , self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self , y_pred , y):
    #clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred , epsilon , 1-epsilon)

    loss = -y * torch.log(y_pred) - (1-y) * torch.log(1-y_pred)
    return loss.mean()

  def update_parameters(self,learning_rate):
    with torch.no_grad():
      self.weights -= learning_rate * self.weights.grad
      self.bias -= learning_rate * self.bias.grad

In [72]:
learning_rate = 0.1
epochs = 50

In [73]:
#training pipeline
#create model
model = MySimpleNN(X_train)

#define loop for epochs
for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(X_train)

  #loss calculate
  loss = model.loss_function(y_pred , y_train)

  #backward pass
  loss.backward()

  #parameters update
  model.update_parameters(learning_rate)

  #reset gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1} Loss: {loss.item()}')

Epoch: 1 Loss: 3.088921043445655
Epoch: 2 Loss: 2.95225175405186
Epoch: 3 Loss: 2.80772739416526
Epoch: 4 Loss: 2.6532292395701367
Epoch: 5 Loss: 2.497015015726526
Epoch: 6 Loss: 2.337353888934368
Epoch: 7 Loss: 2.1755237218024033
Epoch: 8 Loss: 2.014809257512365
Epoch: 9 Loss: 1.8537246714580917
Epoch: 10 Loss: 1.6982905911854316
Epoch: 11 Loss: 1.5470470088093384
Epoch: 12 Loss: 1.4050713112330147
Epoch: 13 Loss: 1.277870033411048
Epoch: 14 Loss: 1.166912165877666
Epoch: 15 Loss: 1.0730186847937666
Epoch: 16 Loss: 0.9959788144418055
Epoch: 17 Loss: 0.9344316943771401
Epoch: 18 Loss: 0.8861381494395528
Epoch: 19 Loss: 0.8484912827726052
Epoch: 20 Loss: 0.8189899442546049
Epoch: 21 Loss: 0.795521742485906
Epoch: 22 Loss: 0.7764589187273042
Epoch: 23 Loss: 0.7606253596450321
Epoch: 24 Loss: 0.7472017731921572
Epoch: 25 Loss: 0.7356236376520717
Epoch: 26 Loss: 0.7254987781037505
Epoch: 27 Loss: 0.7165491331668286
Epoch: 28 Loss: 0.7085720534446385
Epoch: 29 Loss: 0.7014152125673347
Epoch

In [78]:
#evaluation
with torch.no_grad():
  y_pred = model.forward(X_test)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test).float().mean()
  print(f'Accuracy: {accuracy}')

Accuracy: 0.680824875831604
