##Breast_Cancer_Detection
use of Dataset and DataLoader

In [12]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from torch.utils.data import Dataset, DataLoader

In [13]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [14]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [15]:
df.shape

(569, 33)

In [16]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace=True)

In [17]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [19]:
pd.unique(y_train)

array(['B', 'M'], dtype=object)

In [20]:
#scalling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) # use transform not fit_transform as
#we use the same scaler We should use the same scaling parameters (mean & standard deviation) from the training data.

In [21]:
X_train[0]

array([-0.38047784,  2.37249648, -0.43394623, -0.41711999, -0.91074095,
       -1.18045436, -0.87255547, -0.87465712, -0.99455736, -0.89304732,
       -0.64806412,  0.26064693, -0.78927918, -0.5685308 ,  0.5794718 ,
       -0.77313886, -0.60033758, -0.40570099, -0.16830545, -0.78356101,
       -0.49179547,  1.69635348, -0.57220642, -0.50262542, -0.3601711 ,
       -0.97043271, -0.89813324, -0.75736608, -0.79640042, -1.0519418 ])

In [22]:
y_train

552    B
197    M
331    B
237    M
388    B
      ..
362    B
489    M
160    B
440    B
156    M
Name: diagnosis, Length: 455, dtype: object

In [23]:
#label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [24]:
y_train

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,

In [ ]:
#Numpy arrays to PyTorch tensors
# X_train = torch.from_numpy(X_train)
# X_test = torch.from_numpy(X_test)
# y_train = torch.from_numpy(y_test)
# y_test = torch.from_numpy(y_test)

In [25]:
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
y_train= torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [26]:
X_train

tensor([[-0.3805,  2.3725, -0.4339,  ..., -0.7574, -0.7964, -1.0519],
        [ 1.1799,  0.5780,  1.1044,  ..., -0.3399, -0.8599, -1.0103],
        [-0.3188, -0.0107, -0.2987,  ..., -0.2345,  1.1897,  0.4556],
        ...,
        [-0.6802,  0.1856, -0.6580,  ..., -0.5378,  0.4748, -0.2071],
        [-0.9094, -0.5190, -0.8445,  ...,  0.6512, -0.5742,  0.6614],
        [ 1.0623,  0.3180,  1.1044,  ...,  0.5890, -0.7029, -0.3471]])

In [ ]:
# X_train = X_train.to(torch.float32)
# X_test = X_test.to(torch.float32)
# y_train = y_train.to(torch.float32)
# y_test = y_test.to(torch.float32)

In [ ]:
X_train[0]

tensor([-0.5124, -0.2711, -0.5428, -0.5407, -0.6953, -0.6880, -0.6033, -0.6354,
         0.6030, -0.0660, -0.6653, -0.4208, -0.6813, -0.5432, -0.5028, -0.5346,
        -0.3929, -0.5956, -0.3265, -0.4789, -0.5388, -0.0331, -0.6007, -0.5551,
        -0.4581, -0.4596, -0.3536, -0.4642,  0.3514, -0.1164])

In [35]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [36]:
train_dataset = CustomDataset(X_train, y_train)
test_dataset = CustomDataset(X_test, y_test)

In [37]:
train_dataset[0]

(tensor([-0.3805,  2.3725, -0.4339, -0.4171, -0.9107, -1.1805, -0.8726, -0.8747,
         -0.9946, -0.8930, -0.6481,  0.2606, -0.7893, -0.5685,  0.5795, -0.7731,
         -0.6003, -0.4057, -0.1683, -0.7836, -0.4918,  1.6964, -0.5722, -0.5026,
         -0.3602, -0.9704, -0.8981, -0.7574, -0.7964, -1.0519]),
 tensor(0.))

In [39]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True , drop_last=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, drop_last=True)

In [40]:
#defining the model
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features , 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self , x):
    x = self.linear(x)
    x = self.sigmoid(x)
    return x

In [41]:
#loss function
loss_function = nn.BCELoss()

In [42]:
learning_rate = 0.1
epochs = 50

In [43]:
#training pipeline
#create model
model = MySimpleNN(X_train.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)


In [44]:

#define loop for epochs
for epoch in range(epochs):

  for batch_features , batch_labels in train_loader:

      #forward pass
      y_pred = model(batch_features)

      #loss calculate
      loss = loss_function(y_pred , batch_labels.view(-1,1))  #.view(-1,1)  shape will be (row_of_y_train , 1) in this case (455,1)

      #clear grad
      optimizer.zero_grad()

      #backward pass
      loss.backward()

      #parameters update
      optimizer.step()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1} Loss: {loss.item()}')

Epoch: 1 Loss: 0.17321611940860748
Epoch: 2 Loss: 0.12996189296245575
Epoch: 3 Loss: 0.1345777064561844
Epoch: 4 Loss: 0.09932999312877655
Epoch: 5 Loss: 0.05144141614437103
Epoch: 6 Loss: 0.14556342363357544
Epoch: 7 Loss: 0.10800758749246597
Epoch: 8 Loss: 0.061426665633916855
Epoch: 9 Loss: 0.12495932728052139
Epoch: 10 Loss: 0.08734646439552307
Epoch: 11 Loss: 0.07811115682125092
Epoch: 12 Loss: 0.16227909922599792
Epoch: 13 Loss: 0.07886913418769836
Epoch: 14 Loss: 0.05301566794514656
Epoch: 15 Loss: 0.04957237467169762
Epoch: 16 Loss: 0.10294048488140106
Epoch: 17 Loss: 0.09121114015579224
Epoch: 18 Loss: 0.06028251722455025
Epoch: 19 Loss: 0.07228207588195801
Epoch: 20 Loss: 0.030346613377332687
Epoch: 21 Loss: 0.05101616680622101
Epoch: 22 Loss: 0.06262875348329544
Epoch: 23 Loss: 0.05044129490852356
Epoch: 24 Loss: 0.05341401323676109
Epoch: 25 Loss: 0.06539314240217209
Epoch: 26 Loss: 0.07806111872196198
Epoch: 27 Loss: 0.037377774715423584
Epoch: 28 Loss: 0.03429441526532173

In [46]:
#when model is initialized then model.parameters will register all the weights and bias in the form of interations like as below:
for i in model.parameters():
  print(i)

Parameter containing:
tensor([[ 0.6578,  0.6271,  0.4735,  0.5805,  0.3430, -0.0236,  0.5857,  0.4818,
          0.1227, -0.3881,  0.8560, -0.0207,  0.4925,  0.5890,  0.0957, -0.4349,
         -0.1801,  0.1584, -0.1764, -0.4384,  0.9224,  0.8235,  0.5729,  0.5937,
          0.6043,  0.2843,  0.5327,  0.6704,  0.5661,  0.3253]],
       requires_grad=True)
Parameter containing:
tensor([-0.6024], requires_grad=True)


In [47]:
#evaluation
with torch.no_grad():
  for batch_features , batch_labels in test_loader:
    y_pred = model.forward(batch_features)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == batch_labels).float().mean()
    print(f'Accuracy: {accuracy}')

Accuracy: 0.548828125
Accuracy: 0.53125
Accuracy: 0.501953125
